# -*- mode: ruby -*-
# vi: set ft=ruby :
#
#
# Vagrantfile - Servers' infrastructure for DotNet core.
#
#
# Author: 	Rodrigo Alvares de Souza
# 			rsouza01@gmail.com
#
#
# History:
# Version 0.1: 2017/06/24 (rsouza) - First version.
#
#
#

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.librarian_puppet.puppetfile_dir = "librarian"

	config.vm.box = "hashicorp/precise32"

	if Vagrant.has_plugin?("vagrant-librarian-puppet")
		config.librarian_puppet.puppetfile_dir = "librarian"
	end

	config.vm.define :web_dotnet do |web_config|
		web_config.vm.hostname = "webdotnet"
		web_config.vm.network :private_network, :ip => "192.168.33.100"

		web_config.vm.provision "puppet" do |puppet|
			puppet.manifest_file = "web_dotnet.pp"
		end		
	end

end

